### ISSUE TITLE
敢问楼主具体进行什么样的分析呢。

### ISSUE THREAD

**Issue by hs-jyu** [ShenDeng75/GraduationProject#1]

**Comment by ShenDeng75** [comment]
目前的想法是实现：通过输入一组技术词汇(例如：java，大数据，hive等)来推荐一批匹配度较高的招聘岗位。

**Comment by hs-jyu** [comment]
就是词汇统计吗 你这样还不如使用python的wordcloud来展示。楼主有没有什么好的地方学习hadoop啊，带实例那种。

**Comment by ShenDeng75** [comment]
之前用python的jieba分词做过文本分词统计，但是这个项目的数据量比较大不太适合用python做计算，所以用hadoop来处理大数据。你是刚刚入门hadoop，没有搭建过完全分布式集群；还是学习搭建过，写过简单的MapReduce呢？

**Comment by hs-jyu** [comment]
搭建过 写过简单的mapreduce 但是感觉还是不太会 ，理论知识看了很多，找不到合适的项目入手。没有搭建过完全分布式，准备搭建试试看。有没有联系方式呢，能一起学习吗。

**Comment by ShenDeng75** [comment]
我的[HadoopCode仓库](https://github.com/ShenDeng75/HadoopCode)有MapReduce的学习项目代码，和一些MapReduce源码的学习注解；
这是[我的博客](https://www.cnblogs.com/shendeng23/)，里面有我搭建完全分布式的笔记和配置文件，写的可能不是很好，但也可以参考一下
这是我的QQ号：2363521277

**Comment by hs-jyu** [comment]
我加了  问题我关了啊
